services:
  - type: web
    name: nexskill
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
