'use client';
import { useEffect, useState } from 'react';
import MatchRing from '@/components/MatchRing';
import jsPDF from 'jspdf';

function TagInput({ label, values, onChange, placeholder }) {
  const [draft, setDraft] = useState('');

  function add() {
    const v = draft.trim();
    if (!v || values.includes(v)) return;
    onChange([...values, v]);
    setDraft('');
  }

  function remove(v) {
    onChange(values.filter((x) => x !== v));
  }

  return (
    <div>
      <label className="label-eyebrow block mb-2">{label}</label>
      <div className="flex gap-2">
        <input
          className="input-field"
          value={draft}
          placeholder={placeholder}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); add(); } }}
        />
        <button type="button" onClick={add} className="btn-secondary px-4 shrink-0">Add</button>
      </div>
      <div className="flex flex-wrap gap-2 mt-3">
        {values.map((v) => (
          <span key={v} className="inline-flex items-center gap-1.5 bg-indigo-soft text-indigo-deep text-xs font-medium px-2.5 py-1 rounded">
            {v}
            <button type="button" onClick={() => remove(v)} className="hover:text-coral">×</button>
          </span>
        ))}
        {values.length === 0 && <span className="text-sm text-ink/35">None added yet.</span>}
      </div>
    </div>
  );
}

export default function StudentProfilePage() {
  const [profile, setProfile] = useState(null);
  const [user, setUser] = useState(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    fetch('/api/student/profile').then((r) => r.json()).then((d) => { setProfile(d.profile); setUser(d.user); });
  }, []);

  function downloadCvSummary() {
    const doc = new jsPDF();
    const left = 20;
    let y = 22;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text(user?.fullName || 'Student', left, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(110);
    doc.text(user?.email || '', left, y);
    doc.setTextColor(20);
    y += 12;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Profile', left, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    doc.text(`${profile.degree || 'Degree not set'}  ·  Year ${profile.yearOfStudy}  ·  GPA ${profile.gpa}`, left, y);
    y += 6;
    doc.text(`Readiness score: ${profile.readinessScore ?? '—'}/100`, left, y);
    y += 12;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Skills', left, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    const skillsText = (profile.skills || []).join(', ') || 'None listed yet';
    doc.text(doc.splitTextToSize(skillsText, 170), left, y);
    y += doc.splitTextToSize(skillsText, 170).length * 5.5 + 10;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Certifications', left, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    const certsText = (profile.certifications || []).join(', ') || 'None listed yet';
    doc.text(doc.splitTextToSize(certsText, 170), left, y);
    y += doc.splitTextToSize(certsText, 170).length * 5.5 + 10;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Internship preferences', left, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    doc.text(`Domain: ${profile.preferences?.domain || '—'}   Location: ${profile.preferences?.location || '—'}   Duration: ${profile.preferences?.duration || '—'}`, left, y);

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by NexSkill', left, 285);

    doc.save(`${(user?.fullName || 'student').replace(/\s+/g, '_')}_NexSkill_CV_Summary.pdf`);
  }

  function update(key, value) {
    setProfile((p) => ({ ...p, [key]: value }));
    setSaved(false);
  }

  function updatePref(key, value) {
    setProfile((p) => ({ ...p, preferences: { ...p.preferences, [key]: value } }));
    setSaved(false);
  }

  async function save(e) {
    e.preventDefault();
    setSaving(true);
    const res = await fetch('/api/student/profile', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        degree: profile.degree,
        yearOfStudy: Number(profile.yearOfStudy),
        gpa: Number(profile.gpa),
        skills: profile.skills,
        certifications: profile.certifications,
        preferences: profile.preferences,
      }),
    });
    const data = await res.json();
    setProfile(data.profile);
    setSaving(false);
    setSaved(true);
  }

  if (!profile) return <div className="text-ink/40">Loading…</div>;

  return (
    <div className="max-w-2xl space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <div className="label-eyebrow mb-1">Student profile</div>
          <h1 className="font-display text-3xl font-semibold">My Profile</h1>
          <button type="button" onClick={downloadCvSummary} className="text-sm text-indigo font-medium mt-2">
            Download CV summary (PDF) →
          </button>
        </div>
        <MatchRing score={profile.readinessScore || 0} label="Readiness" size={72} />
      </div>

      <form onSubmit={save} className="space-y-6">
        <div className="grid grid-cols-2 gap-4">
          <div className="col-span-2">
            <label className="label-eyebrow block mb-2">Degree programme</label>
            <input className="input-field" value={profile.degree || ''} onChange={(e) => update('degree', e.target.value)} placeholder="e.g. BSc (Hons) Computer Science" required />
          </div>
          <div>
            <label className="label-eyebrow block mb-2">Year of study</label>
            <select className="input-field" value={profile.yearOfStudy || 1} onChange={(e) => update('yearOfStudy', e.target.value)}>
              {[1, 2, 3, 4].map((y) => <option key={y} value={y}>Year {y}</option>)}
            </select>
          </div>
          <div>
            <label className="label-eyebrow block mb-2">GPA (0–4.0)</label>
            <input type="number" step="0.1" min="0" max="4" className="input-field" value={profile.gpa || 0} onChange={(e) => update('gpa', e.target.value)} required />
          </div>
        </div>

        <TagInput label="Skills" values={profile.skills || []} onChange={(v) => update('skills', v)} placeholder="e.g. React" />
        <TagInput label="Certifications" values={profile.certifications || []} onChange={(v) => update('certifications', v)} placeholder="e.g. AWS Certified Cloud Practitioner" />

        <div>
          <div className="label-eyebrow mb-3">Internship preferences</div>
          <div className="grid grid-cols-3 gap-3">
            <input className="input-field" placeholder="Domain" value={profile.preferences?.domain || ''} onChange={(e) => updatePref('domain', e.target.value)} />
            <input className="input-field" placeholder="Location (or Any)" value={profile.preferences?.location || ''} onChange={(e) => updatePref('location', e.target.value)} />
            <input className="input-field" placeholder="Duration" value={profile.preferences?.duration || ''} onChange={(e) => updatePref('duration', e.target.value)} />
          </div>
        </div>

        <div className="flex items-center gap-4">
          <button type="submit" disabled={saving} className="btn-primary disabled:opacity-50">
            {saving ? 'Saving…' : 'Save profile'}
          </button>
          {saved && <span className="text-sm text-indigo font-medium">Saved — readiness score updated.</span>}
        </div>
      </form>
    </div>
  );
}
